services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      sidekiq:
        condition: service_started
      chrome:
        condition: service_started
    networks:
      - app_network
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - app_network
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
  sidekiq:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    depends_on:
      redis:
        condition: service_started
    volumes:
      - .:/rails
    env_file:
      - .env
    networks:
      - app_network
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
      - 5900:5900
    networks:
      - app_network

volumes:
  pg_data:
  redis_data:
  bundle:

networks:
  app_network:
    name: app_network
    external: true
